name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and run SupermarketSimulator
        run: |
          javac src/main/java/SupermarketSimulator.java
          java -cp src main.java.SupermarketSimulator
        continue-on-error: false

      - name: Check exit code
        run: |
          if [ $? -eq 0 ]; then
            echo "SupermarketSimulator ran successfully with exit code 0"
          else
            echo "SupermarketSimulator failed with non-zero exit code"
            exit 1
          fi
